### ISSUE TITLE
A typo in eslint-setting

### ISSUE THREAD

**Issue by Carduelis** [fsubal/eslint-plugin-classnames#1]
From readme file for the [prefer-classnames-function](https://github.com/fsubal/eslint-plugin-classnames/blob/main/docs/rules/prefer-classnames-function.md): 

> You can set `maxSpaceSeparetedClasses` so that you can allow space-separeted

There is a typo in the word `separated` (both in code and docs). It has to have 2 "a" and 2 "e" letters.

This is a misleading thing, that can lead to a lot of frustration if you did not copy the keyword from docs xD

**Comment by fsubal** [comment]
Thank you for sharing!
I could fix it but PR is welcome if you'd like it :)

**Comment by fsubal** [comment]
fixed in 8cc12f5761aa0a18753c66424805da1274238bc4
