### ISSUE TITLE
New rule request: avoiding unnecessary classnames/clsx functions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [fsubal/eslint-plugin-classnames#4]
Spinning off from https://github.com/fsubal/eslint-plugin-classnames/issues/3#issuecomment-1277922718: I'd like to avoid code like this:

```tsx
<Component className={clsx("a", "b")} />
```

I'd be happy to send this in and help set up typed linting!

**Comment by fsubal** [comment]
I think you can set `maxSpaceSeparatedClasses: 2`. Didn't it work ?

**Comment by fsubal** [comment]
(I accidentally deleted my comment so I'm going back and forth now)

> `<Component className={clsx("a", "b")} />`

I first saw this and it can be solved with `maxSeparatedClasses: 2` or so,

https://github.com/fsubal/eslint-plugin-classnames/blob/main/docs/rules/prefer-classnames-function.md

But it seems that you want some type-information-based linting just as pointed out in #3 ?

https://github.com/fsubal/eslint-plugin-classnames/issues/3#issuecomment-1277922718

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
