### ISSUE TITLE
prefer-classnames-function runs for any function inside className prop

### ISSUE THREAD

**Issue by CSFlorin** [fsubal/eslint-plugin-classnames#5]
I'm using https://github.com/joe-bell/cva where you define a variable that resolves to a string of class names to use in a component's `className` prop, and using that triggers this error:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/9855031/211449158-dd945afe-a332-42e9-9eb6-0f2e7be3f0b2.png">

It should only show this error for the function name you define in the lint config:

```
"classnames/prefer-classnames-function": [
  2,
  {
    maxSpaceSeparatedClasses: 1, // default
    functionName: "clsx",
  },
]
```

It looks like the check in https://github.com/fsubal/eslint-plugin-classnames/blob/8cc12f5761aa0a18753c66424805da1274238bc4/lib/rules/prefer-classnames-function.js#L89 should also test for the node's name being functionName

I tried to clone and make the change myself but I can't get the tests to work locally. I get

```
Instead received "undefined" on error with message
```

for every test.

**Comment by CSFlorin** [comment]
Also the maxSpaceSeparatedClasses arg does not work for me. Changing it seems to do nothing.

**Comment by fsubal** [comment]
> Also the maxSpaceSeparatedClasses arg does not work for me. Changing it seems to do nothing.

Sorry I think this has not been published https://github.com/fsubal/eslint-plugin-classnames/commit/8cc12f5761aa0a18753c66424805da1274238bc4

**Comment by CSFlorin** [comment]
Perfect thanks! With that and my PR in the next release, we're good!
